---
- name: Create local dir
  file:
    path: '{{ ansible_user_dir }}/.local/bin'
    state: directory
    mode: '0700'

- name: Copy bin scripts
  copy:
    src: local/bin
    dest: '{{ ansible_user_dir }}/.local'
    mode: preserve
