---
- name: Install rust dependencies
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - curl
      - gcc
  become: true

- name: Check if cargo is installed
  ansible.builtin.stat:
    path: '{{ ansible_user_dir }}/.cargo/bin/cargo'
  register: cargo_bin

- name: Download installer
  when: not cargo_bin.stat.exists
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'

- name: Install rust and cargo
  when: not cargo_bin.stat.exists
  ansible.builtin.command: /tmp/sh.rustup.rs -y --no-modify-path

- name: Copy profile_rust_block
  ansible.builtin.copy:
    src: profile_rust_block
    dest: '/tmp/profile_rust_block'
    mode: '0644'

- name: Reading profile_rust_block file and register it into profile_rust_block variable
  ansible.builtin.command: cat /tmp/profile_rust_block
  register: profile_rust_block
  changed_when: false

- name: Write block in file to .profile
  ansible.builtin.blockinfile:
    path: '{{ ansible_user_dir }}/.profile'
    marker: "# {mark} ANSIBLE MANAGED BLOCK profile_rust_block sourcing"
    block: |
      {{ profile_rust_block.stdout }}
