---
- name: Ensure apps present
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - autofs
      - baobab
      - build-essential
      - cifs-utils
      - curl
      - dconf-editor
      - direnv  # Hook required see https://direnv.net/docs/hook.html - set by zsh role plugin
      - gparted
      - gthumb
      - htop
      - iftop
      - iotop
      - iperf3
      - kazam
      - ncdu
      - nmap
      - openconnect
      - peek
      - pipx
      - pitivi
      - preload
      - safe-rm
      - silversearcher-ag
      - timeshift
      - trash-cli
      - vim
  become: true

- name: Ensure up to date system
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600  # Seconds
    upgrade: dist
    autoclean: true
    autoremove: true
  become: true

- name: Install Python packages
  vars:
    pipx_packages:
      - aws-shell
      - cookiecutter
      - poetry
      - uv
  community.general.pipx:
    name: "{{ item }}"
    state: latest
  with_items: "{{ pipx_packages }}"
