---
- name: Ensure apps present
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - autofs
      - baobab
      - build-essential
      - cifs-utils
      - curl
      - dconf-editor
      - direnv # Hook required see https://direnv.net/docs/hook.html - set by zsh role plugin
      - gparted
      - gthumb
      - htop
      - iftop
      - iotop
      - iperf3
      - kazam
      - ncdu
      - nmap
      - openconnect
      - peek
      - pitivi
      - preload
      - ripgrep
      - safe-rm
      - shellcheck
      - timeshift
      - trash-cli
      - vim
  become: true

- name: Ensure apps absent
  ansible.builtin.apt:
    state: absent
    pkg:
      - dmenu
      - pipx
      - rofi
      - silversearcher-ag
      - terminator
  become: true

- name: Ensure up to date system
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # Seconds
    upgrade: dist
    autoclean: true
    autoremove: true
  become: true

- name: Check if uv is installed
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.local/bin/uv"
  register: ensure_apps_uv_bin

- name: Install Python packages
  when: ensure_apps_uv_bin.stat.exists
  ansible.builtin.command: uv tool install {{ item }}
  with_items:
    - aws-shell
    - cookiecutter
    - poetry
    - tldr
  changed_when: false
