---
- name: Ensure apps present
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - autofs
      - baobab
      - build-essential
      - cifs-utils
      - corkscrew
      - curl
      - dconf-editor
      - flameshot
      - htop
      - iftop
      - iotop
      - iperf3
      - kazam
      - ncdu
      - network-manager-openconnect
      - network-manager-openconnect-gnome
      - nmap
      - openconnect
      - peek
      - pitivi
      - preload
      - safe-rm
      - silversearcher-ag
      - terminator
      - timeshift
      - trash-cli
      - vim
  become: true

- name: Ensure up to date system
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600  # Seconds
    upgrade: "dist"
    autoclean: true
    autoremove: true
  become: true
