---
- name: Ensure apps absent
  apt:
    name: "{{ packages }}"
    state: absent
  become: true
  vars:
    packages:
      - account-plugin-aim
      - account-plugin-facebook
      - account-plugin-flickr
      - account-plugin-google
      - account-plugin-jabber
      - account-plugin-salut
      - account-plugin-yahoo
      - aisleriot
      - cheese
      - evolution
      - evolution-ews
      - evolution-help
      - gfbgraph
      - gnome-boxes
      - gnome-calendar
      - gnome-contacts
      - gnome-dictionary
      - gnome-documents
      - gnome-getting-started-docs
      - gnome-initial-setup
      - gnome-mahjongg
      - gnome-maps
      - gnome-mines
      - gnome-online-miners
      - gnome-photos
      - gnome-software
      - gnome-sudoku
      - gnome-user-docs
      - gnome-user-share
      - gnome-video-effects
      - gnome-weather
      - landscape-client-ui-install
      - rhythmbox
      - shotwell
      - simple-scan
      - thunderbird
      - totem
      - tracker-miners
      - transmission-gtk
      - ubuntu-web-launchers
      - webbrowser-app
      - yelp

- name: Ensure apps present
  apt:
    name: "{{ packages }}"
    state: present
  become: true
  vars:
    packages:
      # - bazelisk
      - build-essential
      - cifs-utils
      - clang-6.0
      - clang-format-6.0
      - clang-tidy-6.0
      - corkscrew
      - curl
      - doxygen
      - git
      - git-lfs
      - gitk
      - htop
      # - hub
      - iftop
      - influxdb
      - iotop
      - kazam
      - meld
      - network-manager-openconnect
      - network-manager-openconnect-gnome
      - nmap
      - openconnect
      - terminator
      - vim
      - zsh

- name: Ensure up to date system
  apt:
    update_cache: true
    cache_valid_time: 3600  # Seconds
    upgrade: "dist"
    autoclean: true
    autoremove: true
  become: true
