---
# yamllint disable rule:line-length
- name: Include brew role
  ansible.builtin.include_role:
    name: brew

- name: Install gh
  community.general.homebrew:
    name:
      - gh
      - git
    state: present
