---
# yamllint disable rule:line-length
- name: "Install repo {{ ansible_role_name }}"
  ansible.builtin.include_role:
    name: apt_add_repo
  vars:
    apt_add_repo_key_url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    apt_add_repo_url: "https://cli.github.com/packages stable main"

- name: Install gh
  ansible.builtin.apt:
    pkg:
      - gh
      - git
  become: true
