---
# yamllint disable rule:line-length
- name: Include brew role
  ansible.builtin.include_role:
    name: brew

- name: Install Bruno
  community.general.homebrew:
    name: bruno
    state: present
