---
- name: Include brew role
  ansible.builtin.include_role:
    name: brew

- name: Install nvm
  community.general.homebrew:
    name:
      - git
      - nvm
    state: present

- name: Create nvm directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.nvm"
    state: directory
    mode: "0755"

- name: Write block in file to rc files
  ansible.builtin.blockinfile:
    backup: true
    path: "{{ item }}"
    create: true
    mode: "0600"
    append_newline: true
    prepend_newline: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK nvm"
    block: |
      export NVM_DIR="$HOME/.nvm"
      NVM_HOMEBREW_PREFIX="{{ homebrew_prefix }}/opt/nvm"
      if [ -s "$NVM_HOMEBREW_PREFIX/nvm.sh" ]; then
        \. "$NVM_HOMEBREW_PREFIX/nvm.sh"
      fi
      if [ -s "$NVM_HOMEBREW_PREFIX/etc/bash_completion.d/nvm" ]; then
        \. "$NVM_HOMEBREW_PREFIX/etc/bash_completion.d/nvm"
      fi
      unset NVM_HOMEBREW_PREFIX
  with_items:
    - "{{ ansible_facts['user_dir'] }}/.zshrc"
    - "{{ ansible_facts['user_dir'] }}/.bashrc"
