---
dist: bionic

language: python

#python:
#  - 3.6
#  - 3.7

cache: pip

services: docker

env:
  matrix:
    - ANSIBLE_ROLE: atom
    - ANSIBLE_ROLE: debug
    - ANSIBLE_ROLE: docker
    - ANSIBLE_ROLE: ensure-apps
    - ANSIBLE_ROLE: git
    - ANSIBLE_ROLE: i3
    - ANSIBLE_ROLE: jetbrains-ide
    - ANSIBLE_ROLE: keepassxc
    - ANSIBLE_ROLE: proxy
    - ANSIBLE_ROLE: ssh
    - ANSIBLE_ROLE: vscode
    - ANSIBLE_ROLE: zsh

before_script:
  - uname -a
  - ansible --version
  - molecule --version

script:
  - cd "./roles/${ANSIBLE_ROLE}"
  - molecule test
