---
dist: bionic

language: python

#python:
#  - 3.6
#  - 3.7

cache: pip

services: docker

matrix:
  fast_finish: true

before_script:
  - uname -a
  - ansible --version
  - molecule --version

script:
  # get list of changed files
  - CHANGED_FILES=($(git diff --name-only $TRAVIS_COMMIT_RANGE))
  - echo $CHANGED_FILES
  - touch changed_roles.txt
  - for file in $CHANGED_FILES; do
      echo $file | cut -d'/' -f-3 >> changed_roles.txt
    done
  - cat changed_roles.txt
  - touch uniq_changed_roles.txt
  - sort changed_roles.txt | uniq > uniq_changed_roles.txt
  - cat uniq_changed_roles.txt
  - readarray -t roles < uniq_changed_roles.txt
  - for role in "${roles[@]}"; do
      pushd "${role}"
      molecule test
      popd
    done

