---
dist: focal

language: python

python:
  - 3.8

cache: pip

services: docker

before_script:
  - uname -a
  - ansible --version
  - molecule --version
  - export

script:
  - ./scripts/test-changed-roles.sh
