[tool.poetry]
name = "config-files"
version = "0.1.0"
description = ""
authors = ["cmuck <cmuckmuck@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
ansible = {version = "^6.2.0", platform = "linux"}

[tool.poetry.dev-dependencies]
docker = {version = "^5.0.3", platform = "linux"}
molecule-docker = {version = "^2.0.0", platform = "linux"}
pre-commit = {version = "^2.20.0", platform = "linux"}
molecule = {version = "^4.0.1", platform = "linux"}
yamllint = {version = "^1.27.1", platform = "linux"}
ansible-lint = {version = "^6.4.0", platform = "linux"}
black = {version = "^22.6.0", platform = "linux"}
isort = {version = "^5.10.1", platform = "linux"}
mdformat = {version = "^0.7.14", platform = "linux"}
mypy = {version = "^0.971", platform = "linux"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
strict = true
files = ["config_files"]

[tool.poetry.scripts]
cf = "config_files.main:main"
