[tool.poetry]
name = "config-files"
version = "0.1.0"
description = ""
authors = ["cmuck <cmuckmuck@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
ansible = "^6.2.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.20.0"
docker = "^5.0.3"
molecule = "^4.0.1"
molecule-docker = "^2.0.0"
yamllint = "^1.27.1"
ansible-lint = "^6.4.0"
black = "^22.6.0"
isort = "^5.10.1"
mdformat = "^0.7.14"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.poetry.scripts]
cf = "config_files.main:main"
