---
# yamllint disable rule:line-length
- name: Include brew role
  ansible.builtin.include_role:
    name: brew

- name: Install delta
  community.general.homebrew:
    name:
      - git
      - git-delta
    state: present

- name: Write block in file to .gitconfig
  ansible.builtin.blockinfile:
    create: true
    mode: "0644"
    path: "{{ ansible_facts['user_dir'] }}/.gitconfig"
    append_newline: true
    prepend_newline: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK delta_gitconfig_block"
    block: |
      [core]
          pager = delta
      [interactive]
          diffFilter = delta --color-only
      [delta]
          features = side-by-side line-numbers decorations
          whitespace-error-style = 22 reverse
      [delta "decorations"]
          commit-decoration-style = bold yellow box ul
          file-style = bold yellow ul
          file-decoration-style = none
