---
# yamllint disable rule:line-length
- name: Include brew role
  ansible.builtin.include_role:
    name: brew

- name: Install lazygit
  community.general.homebrew:
    name: lazygit
    state: present
