---
- name: Setup fact for default proxy environment
  ansible.builtin.set_fact:
    proxy_environment:
      proxy_used: '{{ proxy_used }}'

- name: Debug proxy environment
  ansible.builtin.debug:
    var: proxy_environment

- name: Setup fact fro proxy environment
  ansible.builtin.set_fact:
    proxy_environment:
      http_proxy: '{{ lookup("env","http_proxy") }}'
      https_proxy: '{{ lookup("env","https_proxy")  }}'
      no_proxy: '{{ lookup("env","no_proxy")  }}'
  when:
    - proxy_used | bool

- name: Debug proxy environment
  ansible.builtin.debug:
    var: proxy_environment
#  when:
#    - proxy_used | bool
