---
# yamllint disable rule:line-length
# https://github.com/ansible/ansible/issues/55590
# - name: Set vscode gpg key
#   apt_key:
#     url: "https://packages.microsoft.com/keys/microsoft.asc"
#     state: present
- name: Set facts
  ansible.builtin.set_fact:
    repoid_key: "0xBC528686B50D79E339D3721CEB3E94ADBE1229CF"
    repoid_key_file: /usr/share/keyrings/config_files-vscode.asc

- name: Avoid apt_key deprecation warning once it is removed from your distro, armored keys should use .asc extension, binary
    should use .gpg
  block:
    - name: Install gnupg2 to handle apt key
      ansible.builtin.apt:
        state: present
        update_cache: true
        pkg:
          - gnupg2
      become: true

    - name: Remove apt signing key from default keyring trusted.gpg due to deprecation warning
      ansible.builtin.apt_key:
        id: "{{ repoid_key }}"
        state: absent
      become: true
      changed_when: false

    - name: Download apt key
      ansible.builtin.get_url:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search={{ repoid_key }}
        dest: "{{ repoid_key_file }}"
        mode: "0644"
      become: true
      changed_when: false

    - name: Get DEB architecture
      ansible.builtin.command: dpkg --print-architecture
      register: deb_architecture
      changed_when: deb_architecture.rc != 0

    - name: Add apt source
      ansible.builtin.apt_repository:
        repo: deb [arch={{ deb_architecture.stdout }} signed-by={{ repoid_key_file }}] https://packages.microsoft.com/repos/vscode
          stable main
        filename: config_files-vscode
      become: true

- name: Install vscode
  ansible.builtin.apt:
    name: code
    state: present
  become: true
