---
# yamllint disable rule:line-length
- name: Ensure git is installed
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - apt-utils
      - gnupg2
  become: true

- name: "Install repo {{ ansible_role_name }}"
  ansible.builtin.include_role:
    name: apt_add_repo
  vars:
    apt_add_repo_key: "0xBC528686B50D79E339D3721CEB3E94ADBE1229CF" # gitleaks:allow
    apt_add_repo_url: "https://packages.microsoft.com/repos/vscode stable main"

- name: Install vscode
  ansible.builtin.apt:
    name: code
    state: present
  become: true
