---
- name: 'Install vscode for OS {{ ansible_os_family }}'
  include_tasks: 'os_{{ ansible_os_family }}.yml'
  when: ansible_os_family == "Debian"

- name: Install vscode extensions
  include_tasks: 'install_extensions.yml'
