---
- name: 'Install vscode for Debian'
  include_tasks: 'os_{{ ansible_os_family }}.yml'
  when: ansible_os_family == "Debian"

- name: 'Install vscode for Darwin'
  include_tasks: 'os_{{ ansible_os_family }}.yml'
  when: ansible_os_family == "Darwin"

- name: Install vscode extensions
  include_tasks: 'install_extensions.yml'
