---
# yamllint disable rule:line-length
# https://github.com/ansible/ansible/issues/55590
# - name: Set vscode gpg key
#   apt_key:
#     url: "https://packages.microsoft.com/keys/microsoft.asc"
#     state: present

- name: Fetch vscode public key
  get_url:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    dest: '/etc/apt/trusted.gpg.d'
  become: true

- name: Add vscode apt repository
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
    filename: vscode
  become: true

- name: Install vscode
  apt:
    name: code
    state: present
  become: true
