---
# yamllint disable rule:line-length
# https://github.com/ansible/ansible/issues/55590
# - name: Set vscode gpg key
#   apt_key:
#     url: "https://packages.microsoft.com/keys/microsoft.asc"
#     state: present

- name: Fetch vscode public key
  get_url:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    dest: '/etc/apt/trusted.gpg.d'
  become: true

- name: Add vscode apt repository
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
    filename: vscode
    state: present
    update_cache: true
  become: true

- name: Install vscode
  apt:
    name: code
    state: present
  become: true

- name: Ensure gsettings is present
  apt:
    name: libglib2.0-bin
    state: present
  become: true

- name: Get gsettings favorite-apps
  command: gsettings get org.gnome.shell favorite-apps
  register: gsettings_favorite_apps
  changed_when: false
  ignore_errors: true

- name: Add vscode to favorites
  shell: |
    set -o pipefail
    gsettings set org.gnome.shell favorite-apps "$(gsettings get org.gnome.shell favorite-apps | sed "s/]/,'code.desktop']/")"
  when:
    - gsettings_favorite_apps.rc == 0
    - gsettings_favorite_apps.stdout is not search("code.desktop")
  args:
    executable: /bin/bash
