---
# yamllint disable rule:line-length
- name: Include brew role
  ansible.builtin.include_role:
    name: brew

- name: Install shfmt
  community.general.homebrew:
    name: shfmt
    state: present
