---
# yamllint disable rule:line-length
- name: Include brew role
  ansible.builtin.include_role:
    name: brew

- name: Install hadolint
  community.general.homebrew:
    name: hadolint
    state: present
