---
# yamllint disable rule:line-length
- name: "Install repo {{ ansible_role_name }}"
  ansible.builtin.include_role:
    name: apt_add_repo
  vars:
    apt_add_repo_key: "0xD89C66D0E31FEA2874EBD20561922AB60068FCD6" # gitleaks:allow
    apt_add_repo_url: "http://ppa.launchpad.net/phoerious/keepassxc/ubuntu {{ ansible_lsb.codename }} main"

- name: Install
  ansible.builtin.apt:
    name: keepassxc
    state: present
  become: true
