---
# yamllint disable rule:line-length
- name: Install gnupg to add pub key
  apt:
    name: gnupg
    state: present
  become: true

- name: Add keepass apt-key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: d89c66d0e31fea2874ebd20561922ab60068fcd6
  become: true

- name: Add repository for keepass
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/phoerious/keepassxc/ubuntu bionic main'
    filename: keepass
  become: true

- name: Install keepassxc
  apt:
    name: keepassxc
    state: present
  become: true
