---
# yamllint disable rule:line-length
- name: Check if xcode-select is installed
  stat:
    path: /Library/Developer/CommandLineTools/
  register: xcodeselect

- name: Install xcode-select if missing
  command: xcode-select --install
  when: not xcodeselect.stat.exists

- name: Check if brew is installed
  stat:
    path: /usr/local/bin/brew
  register: brew

- name: Install brew if missing
  command: '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  when: not brew.stat.exists

- name: Check if keepassxc is installed
  stat:
    path: /Applications/KeePassXC.app
  register: keepassxc

- name: Install keepassxc
  homebrew:
    name: keepassxc
    state: present
  when: not keepassxc.stat.exists
