---
# yamllint disable rule:line-length
- name: Install gnupg to add pub key
  apt:
    name: gnupg
    state: present
  become: true

- name: Add keepass apt-key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: d89c66d0e31fea2874ebd20561922ab60068fcd6
  become: true

- name: Add repository for keepass
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/phoerious/keepassxc/ubuntu bionic main'
    filename: keepass
  become: true

- name: Install keepassxc
  apt:
    name: keepassxc
    state: present
  become: true

- name: Ensure gsettings is present
  apt:
    name: libglib2.0-bin
    state: present
  become: true

- name: Get gsettings favorite-apps
  command: gsettings get org.gnome.shell favorite-apps
  register: gsettings_favorite_apps
  changed_when: false
  ignore_errors: true

- name: Add keepassxc to favorites
  shell: |
    set -o pipefail
    gsettings set org.gnome.shell favorite-apps "$(gsettings get org.gnome.shell favorite-apps | sed "s/]/,'org.keepassxc.KeePassXC.desktop']/")"
  when:
    - gsettings_favorite_apps.rc == 0
    - gsettings_favorite_apps.stdout is not search("org.keepassxc.KeePassXC.desktop")
  args:
    executable: /bin/bash
