---
- name: Install ranger
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - ranger
  become: true

- name: Create some dirs
  ansible.builtin.file:
    path: '{{ config_dir }}'
    state: directory
    mode: '0755'

- name: Copy ranger config
  ansible.builtin.copy:
    src: 'rc.conf'
    dest: '{{ config_dir }}'
    mode: '0644'
