---
# yamllint disable rule:line-length
- name: Install exa from Ubuntu 20.10 but works...
  apt:
    deb: http://de.archive.ubuntu.com/ubuntu/pool/universe/r/rust-exa/exa_0.9.0-4_amd64.deb
  become: true
