---
# yamllint disable rule:line-length
# TODO Check again for 24.04
- name: Install exa when Ubuntu == 22.04
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - exa
  become: true
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version|float == 22.04

- name: Set facts
  ansible.builtin.set_fact:
    repoid_key: "0xF2C37BD8BDF01321549242C9AEC82AC78B65E182"
    repoid_key_file: /usr/share/keyrings/config_files-exa.asc

- name: Install exa when Ubuntu < 22.04
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version|float < 22.04
  block:
    - name: Install gnupg2 to handle apt key
      ansible.builtin.apt:
        state: present
        update_cache: true
        pkg:
          - gnupg2
      become: true

    - name: Remove apt signing key from default keyring trusted.gpg due to deprecation warning
      ansible.builtin.apt_key:
        id: "{{ repoid_key }}"
        state: absent
      become: true

    - name: Download apt key
      ansible.builtin.get_url:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search={{ repoid_key }}
        dest: "{{ repoid_key_file }}"
        mode: "0644"
      become: true
      changed_when: false

    - name: Get DEB architecture
      ansible.builtin.command: dpkg --print-architecture
      register: deb_architecture
      changed_when: deb_architecture.rc != 0

    - name: Add apt source
      ansible.builtin.apt_repository:
        repo: deb [arch={{ deb_architecture.stdout }} signed-by={{ repoid_key_file }}] https://ppa.launchpadcontent.net/spvkgn/exa/ubuntu
          {{ ansible_lsb.codename }} main
        filename: config_files-exa
      become: true

    - name: Install exa
      ansible.builtin.apt:
        state: present
        update_cache: true
        pkg:
          - exa
      become: true

- name: Write block in file to rc files
  ansible.builtin.blockinfile:
    backup: true
    path: "{{ item }}"
    create: true
    mode: "0600"
    marker: "# {mark} ANSIBLE MANAGED BLOCK exa"
    block: |
      if command -v exa >/dev/null; then
        # Changing "ls" to "exa"
        alias ls='exa -al --color=always --group-directories-first' # my preferred listing
        alias la='exa -a --color=always --group-directories-first'  # all files and dirs
        alias ll='exa -l --color=always --group-directories-first'  # long format
        alias lt='exa -aT --color=always --group-directories-first' # tree listing
        alias l.='exa -a | egrep "^\."'
        alias ela='exa -a --group-directories-first --icons'
      fi
  with_items:
    - "{{ ansible_user_dir }}/.zshrc"
    - "{{ ansible_user_dir }}/.bashrc"
