---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu_20_04
    image: ubuntu:20.04
#    env:
#      http_proxy: ${http_proxy}
#      https_proxy: ${https_proxy}
#      no_proxy: ${no_proxy}
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    # https://molecule.readthedocs.io/en/stable/configuration.html#scenario
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence skipped, due to task changed is true by apt
    - side_effect
    - verify
    - cleanup
    - destroy
