---
# yamllint disable rule:line-length
- name: Ensure ssh direcotory exists
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/.ssh'
    state: directory
    mode: '0755'

- name: Write SSH config common block
  ansible.builtin.blockinfile:
    create: true
    mode: '0644'
    path: '{{ ansible_user_dir }}/.ssh/config'
    marker: "# {mark} ANSIBLE MANAGED BLOCK common"
    block: |
      Host *
        AddKeysToAgent yes
        IgnoreUnknown UseKeychain
        UseKeychain yes
        IdentityFile ~/.ssh/id_rsa
