---
- name: "Check exist: {{ item }}"
  ansible.builtin.stat:
    path: "{{ item }}"
  register: zsh_dir

- name: "Delete home directory: {{ item }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  when: zsh_dir.stat.exists and zsh_dir.stat.isdir
