---
# yamllint disable rule:line-length
- name: Install zsh dependencies
  apt:
    name: "{{ packages }}"
    state: present
  become: true
  vars:
    packages:
      - curl
      - git
      - zsh

- name: Set default shell for users
  user:
    name: '{{ ansible_user_id }}'
    shell: /bin/zsh
  become: true

- name: Create some dirs
  file:
    path: '{{ ansible_user_dir }}/{{ item }}'
    state: directory
  loop:
    - .config/zsh
    - .local/share/zsh

- name: Write .zshrc for users
  template:
    src: zshrc.j2
    dest: '{{ ansible_user_dir }}/.config/zsh/.zshrc'
    backup: true
  vars:
    oh_my_zsh:
      theme: bira
      plugins:
        - colored-man-pages
        - common-aliases
        - docker
        - fzf
        - sudo
        - web-search
        - zsh-completions
        - zsh-autosuggestions
        - zsh-syntax-highlighting

- name: Clone oh-my-zsh for users
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: '{{ oh_my_zsh_dir }}'  # noqa 401

- name: Clone zsh-completions plugin to users oh-my-zsh directory
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    version: '0.31.0'
    dest: '{{ oh_my_zsh_dir }}/custom/plugins/zsh-completions'
    depth: 1

- name: Clone zsh-autosuggestions plugin to users oh-my-zsh directory
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    version: 'v0.6.4'
    dest: '{{ oh_my_zsh_dir }}/custom/plugins/zsh-autosuggestions'
    depth: 1

- name: Clone zsh-syntax-highlighting plugin to users oh-my-zsh directory
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    version: '0.7.1'
    dest: '{{ oh_my_zsh_dir }}/custom/plugins/zsh-syntax-highlighting'
    depth: 1

- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: '{{ fzf_dir }}'
    depth: 1  # noqa 401

- name: Check fzf is installed
  stat:
    path: '{{ ansible_user_dir }}/.config/fzf'
  register: fzf_installed

- name: Install fzf
  command: "./install --all --xdg"
  args:
    chdir: "{{ fzf_dir }}"
  when: not fzf_installed.stat.exists

- name: Copy .profile
  copy:
    src: profile
    dest: '{{ ansible_user_dir }}/.config/profile'

- name: Write to .profile
  blockinfile:
    path: '{{ ansible_user_dir }}/.profile'
    marker: "# {mark} ANSIBLE MANAGED BLOCK profile sourcing"
    block: |
      source {{ ansible_user_dir }}/.config/profile

- name: Create symbolic link .zprofile
  file:
    src: '{{ ansible_user_dir }}/.profile'
    dest: '{{ ansible_user_dir }}/.zprofile'
    state: link

# Clean up old installations

- name: Check fzf exist in home directory
  stat:
    path: '{{ ansible_user_dir }}/.fzf'
  register: fzf_home_dir

- name: Delete fzf in home directory
  file:
    path: '{{ ansible_user_dir }}/.fzf'
    state: absent
  when: fzf_home_dir.stat.exists and fzf_home_dir.stat.isdir

- name: Check oh-my-zsh exist in home directory
  stat:
    path: '{{ ansible_user_dir }}/.oh-my-zsh'
  register: oh_my_zsh_home_dir

- name: Delete oh-my-zsh in home directory
  file:
    path: '{{ ansible_user_dir }}/.oh-my-zsh'
    state: absent
  when: oh_my_zsh_home_dir.stat.exists and oh_my_zsh_home_dir.stat.isdir
