---
# yamllint disable rule:line-length
- name: Install dependencies
  package:
    name:
      - git
      - zsh
    state: present
  become: true

- name: Clone oh-my-zsh for users
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    version: 903a3e9
    dest: '{{ user_home }}/.oh-my-zsh'
    depth: 1
  become: true
  become_user: '{{ user_name }}'

- name: Set default shell for users
  user:
    name: '{{ user_name }}'
    shell: /bin/zsh
  become: true

- name: Write .zshrc for users
  template:
    src: zshrc.j2
    dest: '{{ user_home }}/.zshrc'
    backup: true
  vars:
    oh_my_zsh:
      theme: bira
      plugins:
        - colored-man-pages
        - common-aliases
        - debian
        - docker
        - git
        - git-extras
        - history
        - sudo
        - web-search
        - zsh-completions  # https://github.com/zsh-users/zsh-completions
        - zsh-autosuggestions  # https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md
