---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: ubuntu_24_04
    image: ubuntu:24.04
  - name: ubuntu_26_04
    image: ubuntu:26.04
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../
verifier:
  name: ansible
