---
- name: Install flameshot
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - flameshot
  become: true

- name: Create config dir for flameshot
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/.config/Dharkael'
    state: directory
    mode: '0755'

- name: Write flameshot configuration
  ansible.builtin.template:
    src: flameshot.ini.j2
    dest: '{{ ansible_user_dir }}/.config/Dharkael/flameshot.ini'
    backup: true
    mode: '0644'

- name: Set dconf shortcut flameshot
  include_role:
    name: dconf
  vars:
    slot: 10
    name: 'flameshot gui'
    command: 'flameshot gui'
    binding: 'Print'
