---
# yamllint disable rule:line-length
- name: "Install repo {{ ansible_role_name }}"
  ansible.builtin.include_role:
    name: apt_add_repo
  vars:
    apt_add_repo_key: "0xF911AB184317630C59970973E363C90F8F1B6217" # gitleaks:allow
    apt_add_repo_url: "https://ppa.launchpadcontent.net/git-core/ppa/ubuntu {{ ansible_lsb.codename }} main"

- name: Ensure git is installed
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - git
      - git-lfs
      - gitk
      - meld
  become: true

- name: Ensure {{ git_user_dir }}
  ansible.builtin.file:
    path: "{{ git_user_dir }}"
    state: directory
    mode: "0755"

- name: Copy OS dependent git config
  ansible.builtin.blockinfile:
    backup: true
    path: "{{ ansible_user_dir }}/.gitconfig"
    create: true
    insertbefore: BOF
    mode: "0644"
    append_newline: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK git"
    block: "{{ lookup('ansible.builtin.file', 'gitconfig') }}"
  changed_when: false

- name: Write block in file to rc files
  ansible.builtin.blockinfile:
    backup: true
    path: "{{ item }}"
    create: true
    mode: "0600"
    append_newline: true
    prepend_newline: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK git"
    block: |
      if command -v git >/dev/null; then
        alias ga='git add'
        alias gap='git add -p'
        alias gs='git status'
        alias gpr='git pull -r'
        alias gl='git lg'
        alias glo='git log --oneline'
        alias gcm='git commit -m'
        alias pear='git pair '
        alias gra='git commit --amend --reset-author --no-edit'
        alias gco='git checkout'
        alias hangon='git stash save -u'
        alias gsp='git stash pop'
        alias grc='git rebase --continue'
        alias gclean='git clean -df'
        alias gup='gco main && gpr && gco -'
        alias unwip='git reset HEAD~'
        alias unroll='git reset HEAD~ --hard'
        alias gpfwl='git push --force-with-lease'
        alias glt='git describe --tags --abbrev=0'
      fi
  with_items:
    - "{{ ansible_user_dir }}/.zshrc"
    - "{{ ansible_user_dir }}/.bashrc"

- name: Configure user.name in ~/.gitconfig
  community.general.git_config:
    scope: global
    name: "user.name"
    value: "{{ git_user_name }}"
  changed_when: false

- name: Configure user.email in ~/.gitconfig
  community.general.git_config:
    scope: global
    name: "user.email"
    value: "{{ git_user_email }}"
  changed_when: false
