---
# yamllint disable rule:line-length
- name: Ensure git is installed
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - git
      - git-lfs
      - gitk
      - meld
  become: true

- name: Ensure {{ git_user_dir }} exists
  ansible.builtin.file:
    path: '{{ git_user_dir }}'
    state: directory
    mode: '0755'

- name: Copy OS dependent git config
  ansible.builtin.copy:
    src: 'gitconfig'
    dest: '{{ ansible_user_dir }}/.gitconfig'
    mode: '0644'
    backup: true
  changed_when: false

- name: Configure user.name in ~/.gitconfig
  community.general.git_config:
    scope: global
    name: 'user.name'
    value: '{{ git_user_name }}'
  changed_when: false

- name: Configure user.email in ~/.gitconfig
  community.general.git_config:
    scope: global
    name: 'user.email'
    value: '{{ git_user_email }}'
  changed_when: false
