---
- name: 'Install and configure git for Debian'
  include_tasks: 'os_{{ ansible_os_family }}.yml'
  when: ansible_os_family == "Debian"

- name: 'Install and configure git for Darwin'
  include_tasks: 'os_{{ ansible_os_family }}.yml'
  when: ansible_os_family == "Darwin"
