---
- name: Ensure git is installed
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - git
      - git-lfs
      - gitk
      - meld
  become: true

- name: Ensure {{ git_user_dir }} exists
  ansible.builtin.file:
    path: '{{ git_user_dir }}'
    state: directory
    mode: '0755'

- name: Copy OS independent git common config to {{ git_user_dir }}
  ansible.builtin.copy:
    src: 'gitconfig-common'
    dest: '{{ git_user_dir }}'
    mode: '0644'

- name: Copy OS dependent git config
  ansible.builtin.copy:
    src: 'gitconfig-{{ ansible_os_family }}'
    dest: '{{ ansible_user_dir }}/.gitconfig'
    force: false
    mode: '0644'

- name: Configure user.name in ~/.gitconfig
  community.general.git_config:
    scope: global
    name: 'user.name'
    value: '{{ git_user_name }}'

- name: Configure user.email in ~/.gitconfig
  community.general.git_config:
    scope: global
    name: 'user.email'
    value: '{{ git_user_email }}'
