---
- name: 'Install atom for Debian'
  include_tasks: 'os_{{ ansible_os_family }}.yml'
  when: ansible_os_family == "Debian"

- name: 'Install atom for Darwin'
  include_tasks: 'os_{{ ansible_os_family }}.yml'
  when: ansible_os_family == "Darwin"

- name: Copy atom extensions
  include_tasks: 'copy_extensions.yml'
