---
- name: 'Install atom OS {{ ansible_os_family }}'
  include_tasks: 'os_{{ ansible_os_family }}.yml'
  when: ansible_os_family == "Debian"

- name: Copy atom extensions
  include_tasks: 'copy_extensions.yml'
