---
# yamllint disable rule:line-length

# - name: Fetch atom public key
#  get_url:
#    url: 'https://packagecloud.io/AtomEditor/atom/gpgkey'
#    dest: '/etc/apt/trusted.gpg.d/atom.gpg'
#    #use_proxy: true
#  become: true

- name: Install dependencies
  apt:
    state: present
    update_cache: true
    pkg:
      - apt-transport-https
      - gnupg
  become: true

- name: Install atom apt key
  apt_key:
    url: 'https://packagecloud.io/AtomEditor/atom/gpgkey'
    state: present
  become: true

- name: Get DEB architecture
  command: dpkg --print-architecture
  register: deb_architecture
  changed_when: deb_architecture.rc != 0

- name: Add atom apt repository
  apt_repository:
    repo: 'deb [arch={{ deb_architecture.stdout }}] https://packagecloud.io/AtomEditor/atom/any/ any main'
    filename: atom
  become: true

- name: Install atom
  apt:
    name: atom
    state: present
  become: true

- name: Ensure {{ atom_user_dir }} exists
  file:
    path: '{{ atom_user_dir }}'
    state: directory
    mode: '0700'

- name: Copy atom plugins to {{ atom_user_dir }}
  copy:
    src: packages.cson
    dest: '{{ atom_user_dir }}'
    mode: '0600'
