---
- name: Install terminator
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - terminator
  become: true

- name: Create config dir for terminator
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/terminator"
    state: directory
    mode: "0755"

- name: Copy terminator config
  ansible.builtin.copy:
    src: config/terminator/config
    dest: "{{ ansible_user_dir }}/.config/terminator"
    mode: preserve
    backup: true
