---
- name: Install rofi
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - rofi
  become: true

- name: Create config dir for rofi
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/.config/rofi'
    state: directory
    mode: '0755'

- name: Copy rofi config
  ansible.builtin.copy:
    src: config/rofi/config
    dest: '{{ ansible_user_dir }}/.config/rofi'
    mode: '0644'
    backup: true
