---
- name: Converge
  hosts: all
  tasks:
    - name: Include apt_add_repo role
      ansible.builtin.include_role:
        name: apt_add_repo
      vars:
        apt_add_repo_key: "0xF911AB184317630C59970973E363C90F8F1B6217" # gitleaks:allow
        apt_add_repo_url: "https://ppa.launchpadcontent.net/git-core/ppa/ubuntu {{ ansible_lsb.codename }} main"
  environment: "{{ proxy_environment }}"
