---
- name: Install dependencies
  ansible.builtin.apt:
    state: present
    pkg:
      - git
      - python3
      - python3-pip
    update_cache: true
  become: true

- name: Download lunarvim install script
  ansible.builtin.get_url:
    url: https://pyenv.run
    dest: /tmp/install_pyenv.sh
    mode: '0755'
  changed_when: false
  register: pyenv

- name: Install pyenv
  ansible.builtin.command: '{{ pyenv.dest }}'
  changed_when: false

- name: Write block in file to rc files
  ansible.builtin.blockinfile:
    backup: true
    path: '{{ item }}'
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK pyenv"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
      if command -v pyenv >/dev/null; then
        eval "$(pyenv init -)"
        # eval "$(pyenv virtualenv-init -)"
      fi
  with_items:
    - '{{ ansible_user_dir }}/.zshrc'
    - '{{ ansible_user_dir }}/.bashrc'
