---
- name: Debug proxy_environment
  ansible.builtin.debug:
    var: proxy_environment

- name: Debug ansible_env
  ansible.builtin.debug:
    var: ansible_env

- name: Debug lookup
  ansible.builtin.debug:
    var: tmp
  vars:
    tmp: "{{ lookup('env', 'http_proxy') }}"

- name: Debug environment
  ansible.builtin.debug:
    var: environment
