---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: ubuntu_22_04
    image: ubuntu:22.04
  - name: ubuntu_24_04
    image: ubuntu:24.04
#    env:
#      http_proxy: ${http_proxy}
#      https_proxy: ${https_proxy}
#      no_proxy: ${no_proxy}
provisioner:
  name: ansible
verifier:
  name: ansible
