---
# yamllint disable rule:line-length
- name: Install docker dependencies
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
  become: true

- name: Set facts
  ansible.builtin.set_fact:
    repoid_key: "0x9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    repoid_key_file: /usr/share/keyrings/config_files-docker.asc

- name: Avoid apt_key deprecation warning once it is removed from your distro, armored keys should use .asc extension, binary should use .gpg
  block:
    - name: Install gnupg2 to handle apt key
      ansible.builtin.apt:
        state: present
        update_cache: true
        pkg:
          - gnupg2
      become: true

    - name: Remove apt signing key from default keyring trusted.gpg due to deprecation warning
      ansible.builtin.apt_key:
        id: "{{ repoid_key }}"
        state: absent
      become: true

    - name: Download apt key
      ansible.builtin.get_url:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search={{ repoid_key }}
        dest: "{{ repoid_key_file }}"
        mode: "0644"
      become: true
      changed_when: false

    - name: Get DEB architecture
      ansible.builtin.command: dpkg --print-architecture
      register: deb_architecture
      changed_when: deb_architecture.rc != 0

    - name: Add apt source
      ansible.builtin.apt_repository:
        repo: deb [arch={{ deb_architecture.stdout }} signed-by={{ repoid_key_file }}] https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_lsb.codename
          }} stable
        filename: config_files-docker
      become: true

- name: Install docker
  ansible.builtin.apt:
    name: docker-ce
    state: present
  become: true

- name: Ensure group docker exists
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: "Add to docker group: {{ ansible_user_id }}"
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - docker
    append: true
  become: true

# Reboot required to become effective
