---
# yamllint disable rule:line-length
- name: Install docker dependencies
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
  become: true

- name: "Install repo {{ ansible_role_name }}"
  ansible.builtin.include_role:
    name: apt_add_repo
  vars:
    apt_add_repo_key: "0x9DC858229FC7DD38854AE2D88D81803C0EBFCD88" # gitleaks:allow
    apt_add_repo_url: "https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_lsb.codename }} stable"

- name: Install docker
  ansible.builtin.apt:
    name: docker-ce
    state: present
  become: true

- name: Ensure group docker exists
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: "Add to docker group: {{ ansible_user_id }}"
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - docker
    append: true
  become: true

# Reboot required to become effective
