---
# yamllint disable rule:line-length
- name: Check if xcode-select is installed
  stat:
    path: /Library/Developer/CommandLineTools/
  register: xcodeselect

- name: Install xcode-select if missing
  command: xcode-select --install
  when: not xcodeselect.stat.exists

- name: Check if brew is installed
  stat:
    path: /usr/local/bin/brew
  register: brew

- name: Install brew if missing
  command: '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  when: not brew.stat.exists

- name: Check if docker is installed
  stat:
    path: /Applications/Docker.app
  register: docker

- name: Install docker
  homebrew_cask:
    name: docker
    state: present
  when: not docker.stat.exists
