---
- name: "Setup machine for developing"
  hosts: all
  roles:
    - name: Install Jetbrains Toolbox
      role: jetbrains
      tags: [jetbrains]
    - name: Install vscode
      role: vscode
      tags: [vscode]
    - name: Install zsh
      role: zsh
      tags: [zsh]
    - name: Install ranger
      role: ranger
      tags: [ranger]
    - name: Install neovim
      role: neovim
      tags: [neovim]
    - name: Install git
      role: git
      tags: [git]
    - name: Install keepassxc
      role: keepassxc
      tags: [keepassxc]
    - name: Ensure ssh
      role: ssh
      tags: [ssh]
    - name: Ensure apps
      role: ensure_apps
      tags: [ensure-apps]
    - name: Install docker
      role: docker
      tags: [docker]
    - name: Install flameshot
      role: flameshot
      tags: [flameshot]
    - name: Install bat
      role: bat
      tags: [bat]
    - name: Install terminator
      role: terminator
      tags: [terminator]
    - name: Install scripts
      role: scripts
      tags: [scripts]
    - name: Install delta
      role: delta
      tags: [delta]
    - name: Install exa
      role: exa
      tags: [exa]
    - name: Install gh
      role: gh
      tags: [gh]
    - name: Install rust
      role: rust
      tags: [rust]
    - name: Install rofi
      role: rofi
      tags: [rofi]
    - name: Install gifgen
      role: gifgen
      tags: [gifgen]
    - name: Install lazygit
      role: lazygit
      tags: [lazygit]
#    - name: Install starship
#      role: starship
#      tags: [starship]
#    - name: Install i3 window manager
#      role: i3
#      tags: [i3]
  environment: '{{ proxy_environment }}'
