---
- name: Setup machine for developing
  hosts: all
  vars:
    default_git_user_name: "cmuck"
    default_git_user_email: "cmuckmuck@gmail.com"
  vars_prompt:
    - name: "git_user_name"
      prompt: "Enter your git user name"
      default: "{{ default_git_user_name }}"
    - name: "git_user_email"
      prompt: "Enter your git user email"
      default: "{{ default_git_user_email }}"
  roles:
    - name: Install Jetbrains Toolbox
      role: jetbrains
      tags: [jetbrains]
    - name: Install vscode
      role: vscode
      tags: [vscode]
    - name: Install zsh
      role: zsh
      tags: [zsh]
    - name: Install yazi
      role: yazi
      tags: [yazi]
    - name: Install lazygit
      role: lazygit
      tags: [lazygit]
    - name: Install rust
      role: rust
      tags: [rust]
    - name: Install eza
      role: eza
      tags: [eza]
    - name: Install nvim
      role: nvim
      tags: [nvim]
    - name: Install nvchad
      role: nvchad
      tags: [nvchad]
    - name: Install gogh
      role: gogh
      tags: [gogh]
    - name: Install nerdfonts
      role: nerdfonts
      tags: [nerdfonts]
    - name: Install git
      role: git
      tags: [git]
    - name: Install keepassxc
      role: keepassxc
      tags: [keepassxc]
    - name: Ensure apps
      role: ensure_apps
      tags: [ensure-apps]
    - name: Install docker
      role: docker
      tags: [docker]
    - name: Install flameshot
      role: flameshot
      tags: [flameshot]
    - name: Install bat
      role: bat
      tags: [bat]
    - name: Install scripts
      role: scripts
      tags: [scripts]
    - name: Install delta
      role: delta
      tags: [delta]
    - name: Install gh
      role: gh
      tags: [gh]
    - name: Install rofi
      role: rofi
      tags: [rofi]
    - name: Install gifgen
      role: gifgen
      tags: [gifgen]
    - name: Install tmux
      role: tmux
      tags: [tmux]
    - name: Install Nextcloud client
      role: nextcloud
      tags: [nextcloud]
    - name: Install hadolint
      role: hadolint
      tags: [hadolint]
    - name: Install bitwarden
      role: bitwarden
      tags: [bitwarden]
    - name: Install discord
      role: discord
      tags: [discord]
    - name: Install Obsidian
      role: obsidian
      tags: [obsidian]
    - name: Install starship
      role: starship
      tags: [starship]
  environment: "{{ proxy_environment }}"
