---
- name: "Setup machine for developing"
  hosts: all
  vars:
    default_git_user_name: 'Christian Muck'
    default_git_user_email: 'cmuckmuck@gmail.com'
  vars_prompt:
    - name: "git_user_name"
      prompt: "Enter your git user name"
      default: '{{ default_git_user_name }}'
    - name: "git_user_email"
      prompt: "Enter your git user email"
      default: '{{ default_git_user_email }}'
  roles:
    - name: Install Jetbrains Toolbox
      role: jetbrains
      tags: [jetbrains]
    - name: Install vscode
      role: vscode
      tags: [vscode]
    - name: Install zsh
      role: zsh
      tags: [zsh]
    - name: Install ranger
      role: ranger
      tags: [ranger]
    - name: Install neovim
      role: neovim
      tags: [neovim]
    - name: Install git
      role: git
      tags: [git]
    - name: Install keepassxc
      role: keepassxc
      tags: [keepassxc]
    - name: Ensure ssh
      role: ssh
      tags: [ssh]
    - name: Ensure apps
      role: ensure_apps
      tags: [ensure-apps]
    - name: Install docker
      role: docker
      tags: [docker]
    - name: Install flameshot
      role: flameshot
      tags: [flameshot]
    - name: Install bat
      role: bat
      tags: [bat]
    - name: Install terminator
      role: terminator
      tags: [terminator]
    - name: Install scripts
      role: scripts
      tags: [scripts]
    - name: Install delta
      role: delta
      tags: [delta]
  environment: '{{ proxy_environment }}'
