---
- name: "Inventory"
  hosts: all
  tasks:
    - debug:
        msg: '{{ ansible_facts }}'
    - debug:
        msg: "Saving inventory to: {{ ansible_user_dir }}/Desktop/inventory.json"
    - name: Save all facts to host specific file
      copy:
        content: '{{ ansible_facts | to_nice_json  }}'
        dest: '{{ ansible_user_dir }}/Desktop/inventory.json'
      delegate_to: localhost

# Alternative: ansible localhost -m setup > inventory.yaml
