---
- name: Include brew role
  ansible.builtin.include_role:
    name: brew

- name: Install neovim
  community.general.homebrew:
    name: neovim
    state: present

- name: Write block in file to rc files
  ansible.builtin.blockinfile:
    backup: true
    path: "{{ item }}"
    create: true
    mode: "0600"
    append_newline: true
    prepend_newline: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK nvim"
    block: |
      command -v nvim >/dev/null && alias vim='nvim' vimdiff='nvim -d' n='nvim'
  with_items:
    - "{{ ansible_facts['user_dir'] }}/.zshrc"
    - "{{ ansible_facts['user_dir'] }}/.bashrc"
