---
- name: Remove neovim when installed by package manager not to conflict
  ansible.builtin.apt:
    state: absent
    pkg:
      - neovim
      - neovim-runtime
  become: true

- name: Remove config directories
  ansible.builtin.file:
      path: "{{ item }}"
      state: absent
  with_items:
    - "/opt/nvim-linux64"
  become: true
  changed_when: false

- name: Check latest neovim version
  uri:
    url: https://api.github.com/repos/neovim/neovim/releases/latest
  register: neovim_latest

- name: Download neovim
  ansible.builtin.unarchive:
    src: "{{ neovim_latest.json.assets[0].browser_download_url }}"
    dest: "/opt"
    remote_src: yes
  changed_when: false
  become: true

- name: Write block in file to rc files
  ansible.builtin.blockinfile:
    backup: true
    path: '{{ item }}'
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK nvim"
    block: |
      export PATH="$PATH:/opt/nvim-linux64/bin"
      command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"
  with_items:
    - '{{ ansible_user_dir }}/.zshrc'
    - '{{ ansible_user_dir }}/.bashrc'
