---
- name: Install neovim
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - neovim
      - vim
  become: true

- name: Create some dirs
  ansible.builtin.file:
    path: '{{ config_dir }}'
    state: directory
    mode: '0755'

- name: Copy neovim config
  ansible.builtin.copy:
    src: 'init.vim'
    dest: '{{ config_dir }}'
    mode: '0644'
