---
- name: Install neovim
  apt:
    state: present
    update_cache: true
    pkg:
      - neovim
      - vim
  become: true

- name: Create some dirs
  file:
    path: '{{ config_dir }}'
    state: directory
    mode: '0700'

- name: Copy neovim config
  copy:
    src: 'init.vim'
    dest: '{{ config_dir }}'
    mode: '0600'
