---
- name: Install neovim
  apt:
    name: "{{ packages }}"
    state: present
  become: true
  vars:
    packages:
      - neovim
      - vim

- name: Create some dirs
  file:
    path: '{{ config_dir }}'
    state: directory

- name: Copy neovim config
  copy:
    src: 'init.vim'
    dest: '{{ config_dir }}'
