---
name: CI

on:
  schedule:
    - cron: "0 3 * * *"
  pull_request:
  workflow_dispatch:
jobs:
  molecule:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync

      - name: Get changed files
        id: changed-files
        if: ${{ github.event_name == 'pull_request' }}
        uses: tj-actions/changed-files@v46

      - name: Run pre-commit
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        run: |
          uv run pre-commit run --all-files

      - name: Testing roles - pull-request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          uv run cf-molecule ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Testing roles - scheduled
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        run: |
          uv run cf-molecule
