---
name: CI

on:
  schedule:
    - cron: '0 3 * * *'
  pull_request:
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install -r dev-requirements.txt
      - uses: mfinelli/setup-shfmt@v2
      - id: files
        name: Get changed files
        if: ${{ github.event_name == 'pull_request' }}
        uses: jitterbit/get-changed-files@v1
      - name: Testing roles - pull-request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ./scripts/test-roles.sh ${{ steps.files.outputs.all }}
      - name: Testing roles - scheduled
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        run: |
          ./scripts/test-roles.sh
