---
name: CI

on:
  schedule:
    - cron: "0 3 * * *"
  pull_request:
  workflow_dispatch:
jobs:
  molecule:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@auto-environment

      - name: Install the project
        run: uv sync

      - uses: pre-commit/action@v3.0.1

      - id: files
        name: Get changed files
        if: ${{ github.event_name == 'pull_request' }}
        uses: jitterbit/get-changed-files@v1

      - name: Testing roles - pull-request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ./scripts/test-roles.sh ${{ steps.files.outputs.all }}

      - name: Testing roles - scheduled
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        run: |
          ./scripts/test-roles.sh
