---
name: CI

on:
  schedule:
    - cron: '0 3 * * *'
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: mfinelli/setup-shfmt@v1
      - uses: pre-commit/action@v2.0.3

  molecule:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          # python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt
      - name: Some debug output
        run: |
          uname -a
          ansible --version
          molecule --version
          #export
      - id: files
        name: Get changed files
        uses: jitterbit/get-changed-files@v1
        if: ${{ github.event_name == 'pull_request' }}
      - name: Testing roles
        run: |
          ./scripts/test-roles.sh ${{ steps.files.outputs.all }}
        if: ${{ github.event_name == 'pull_request' }}
      - name: Testing roles
        run: |
          ./scripts/test-roles.sh
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
