---
- name: Install bat
  ansible.builtin.apt:
    name: bat
    state: present
    update_cache: true
  become: true

- name: Write block in file to rc files - test
  ansible.builtin.blockinfile:
    backup: true
    path: "{{ item }}"
    create: true
    mode: "0600"
    append_newline: true
    prepend_newline: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK bat"
    block: |
      command -v bat >/dev/null && alias bc="bat"
      command -v batcat >/dev/null && alias bc="batcat"
  with_items:
    - "{{ ansible_user_dir }}/.zshrc"
    - "{{ ansible_user_dir }}/.bashrc"
